language: python

python:
 - "2.7"

before_script:
 - sudo add-apt-repository -y ppa:gviz-adm/graphviz-dev
 - sudo apt-get update -q
 - apt-cache policy libgraphviz4
 - for i in /etc/apt/preferences.d/*; do echo "$i"; cat "$i"; done
 - sudo apt-get install libgraphviz4 graphviz

script: true
