language: python

python:
 - "2.7"

before_script:
 - sudo add-apt-repository -y ppa:gviz-adm/graphviz-dev
 - sudo apt-get update -q
 - cat /etc/apt/preferences
 - cat /etc/apt/preferences.d
 - sudo apt-get install libgraphviz4 graphviz

script: true
