language: python

python:
 - "2.7"

before_script:
 - sudo add-apt-repository -y ppa:gviz-adm/graphviz-dev
 - sudo apt-get update -q
 - yes "" | sudo apt-get dist-upgrade -q
 - sudo apt-get install graphviz

script: true
